# DISPLAYING THE PROGRAM TITLE
print("*** PROGRAMA QUE DETERMINA QUÉ CANTIDAD DE ALUMNOS NO TIENEN DERECHO A NIVELACIÓN ***")

# ⚠⚠⚠⚠⚠ EL CASO NO DA LOS CRITERIOS PARA DEFINIR QUÉ ALUMNOS TIENEN DERECHO AL EXAMEN DE NIVELACION

# ⚠⚠⚠⚠⚠ HASTA OBTENER MAYOR INFORMACIÓN EL PROGRAMA SE VA A LIMITAR A LEER LAS CALIFICACIONES Y MOSTRAR LA INFORMACIÓN CAPTADA

i = 0

while i < 40:
    i += 1
